//Firebase Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOADING = 'LOADING';
export const SELECT_LOADING = 'SELECT_LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

// Attributes

export const ATTRIBUTE_GET_SUCCESS = 'ATTRIBUTE_GET_SUCCESS';
export const ATTRIBUTE_GET_FAILURE = 'ATTRIBUTE_GET_FAILURE';

export const ATTRIBUTE_SAVE_SUCCESS = 'ATTRIBUTE_SAVE_SUCCESS';
export const ATTRIBUTE_SAVE_FAILURE = 'ATTRIBUTE_SAVE_FAILURE';

export const SELECTED_ATTRIBUTE_SET_SUCCESS = 'SELECTED_ATTRIBUTE_SET_SUCCESS';
export const SELECTED_ATTRIBUTE_SET_FAILURE = 'SELECTED_ATTRIBUTE_SET_FAILURE';

export const ATTRIBUTE_CREATE_MAGE_SUCCESS = 'ATTRIBUTE_CREATE_MAGE_SUCCESS';
export const ATTRIBUTE_CREATE_MAGE_FAILURE = 'ATTRIBUTE_CREATE_MAGE_FAILURE';

export const DROPDOWN_VALUES_SUCCESS = 'DROPDOWN_VALUES_SUCCESS';
export const DROPDOWN_VALUES_FAILURE = 'DROPDOWN_VALUES_FAILURE';

export const ATTRIBUTE_UPDATE_SUCCESS = 'ATTRIBUTE_UPDATE_SUCCESS';
export const ATTRIBUTE_UPDATE_FAILURE = 'ATTRIBUTE_UPDATE_FAILURE';

export const ATTRIBUTE_SYNC_SUCCESS = 'ATTRIBUTE_SYNC_SUCCESS';
export const ATTRIBUTE_SYNC_FAILURE = 'ATTRIBUTE_SYNC_FAILURE';

export const ATTRIBUTE_DELETE_SUCCESS = 'ATTRIBUTE_DELETE_SUCCESS';
export const ATTRIBUTE_DELETE_FAILURE = 'ATTRIBUTE_DELETE_FAILURE';

export const SEARCH_ATTRIBUTES = 'SEARCH_ATTRIBUTES';

// Categories

export const GET_SITE_MAP_SUCCESS = 'GET_SITE_MAP_SUCCESS';
export const GET_SITE_MAP_FAILURE = 'GET_SITE_MAP_FAILURE';

export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const CATEGORIES_SAVE_SUCCESS = 'CATEGORIES_SAVE_SUCCESS';
export const CATEGORIES_SAVE_FAILURE = 'CATEGORIES_SAVE_FAILURE';

export const CATEGORIES_UPDATE_SUCCESS = 'CATEGORIES_UPDATE_SUCCESS';
export const CATEGORIES_UPDATE_FAILURE = 'CATEGORIES_UPDATE_FAILURE';

export const CATEGORIES_DELETE_SUCCESS = 'CATEGORIES_DELETE_SUCCESS';
export const CATEGORIES_DELETE_FAILURE = 'CATEGORIES_DELETE_FAILURE';

// Channels

export const CHANNELS_GET_SUCCESS = 'CHANNELS_GET_SUCCESS';
export const CHANNELS_GET_FAILURE = 'CHANNELS_GET_FAILURE';

// Products

export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_GET_FAILURE = 'PRODUCTS_GET_FAILURE';

export const PRODUCTS_DUPLICATE_SUCCESS = 'PRODUCTS_DUPLICATE_SUCCESS';
export const PRODUCTS_DUPLICATE_FAILURE = 'PRODUCTS_DUPLICATE_FAILURE';

export const VARIATIONS_GET_SUCCESS = 'VARIATIONS_GET_SUCCESS';
export const VARIATIONS_GET_FAILURE = 'VARIATIONS_GET_FAILURE';

export const PRODUCTS_VARIATIONS_GET_SUCCESS = 'PRODUCTS_VARIATIONS_GET_SUCCESS';
export const PRODUCTS_VARIATIONS_GET_FAILURE = 'PRODUCTS_VARIATIONS_GET_FAILURE';

export const PRODUCTS_VARIATIONS_DELETE_SUCCESS = 'PRODUCTS_VARIATIONS_DELETE_SUCCESS';
export const PRODUCTS_VARIATIONS_DELETE_FAILURE = 'PRODUCTS_VARIATIONS_DELETE_FAILURE';

export const PRODUCTS_SEARCH_SUCCESS = 'PRODUCTS_SEARCH_SUCCESS';
export const PRODUCTS_SEARCH_FAILURE = 'PRODUCTS_SEARCH_FAILURE';

export const PRODUCTS_URL_KEYS_SUCCESS = 'PRODUCTS_URL_KEYS_SUCCESS';
export const PRODUCTS_URL_KEYS_FAILURE = 'PRODUCTS_URL_KEYS_FAILURE';

export const SET_USER_CAN_ENTER_URL_KEY = 'SET_USER_CAN_ENTER_URL_KEY'

export const PRODUCT_IMAGES_SORT_ORDER_UPDATE_SUCCESS = 'PRODUCT_IMAGES_SORT_ORDER_UPDATE_SUCCESS';
export const PRODUCT_IMAGES_SORT_ORDER_UPDATE_FAILURE = 'PRODUCT_IMAGES_SORT_ORDER_UPDATE_FAILURE';

export const PRODUCT_VIDEOS_SORT_ORDER_UPDATE_SUCCESS = 'PRODUCT_VIDEOS_SORT_ORDER_UPDATE_SUCCESS';
export const PRODUCT_VIDEOS_SORT_ORDER_UPDATE_FAILURE = 'PRODUCT_VIDEOS_SORT_ORDER_UPDATE_FAILURE';

export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAILURE = 'PRODUCT_GET_FAILURE';

export const VARIATION_GET_SUCCESS = 'VARIATION_GET_SUCCESS';
export const VARIATION_GET_FAILURE = 'VARIATION_GET_FAILURE';

export const SEARCH_VARIATION_SUCCESS = 'SEARCH_VARIATION_SUCCESS';
export const SEARCH_VARIATION_FAILURE = 'SEARCH_VARIATION_FAILURE';

export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAILURE = 'PRODUCT_SAVE_FAILURE';

export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILURE = 'PRODUCT_UPDATE_FAILURE';

export const VARIATION_UPDATE_SUCCESS = 'VARIATION_UPDATE_SUCCESS';
export const VARIATION_UPDATE_FAILURE = 'VARIATION_UPDATE_FAILURE';

export const AMAZON_LOOKUP_SUCCESS = 'AMAZON_LOOKUP_SUCCESS';
export const AMAZON_LOOKUP_FAILURE = 'AMAZON_LOOKUP_FAILURE';

export const PRODUCT_BULK_SUCCESS = 'PRODUCT_BULK_SUCCESS';
export const PRODUCT_BULK_FAILURE = 'PRODUCT_BULK_FAILURE';

export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS';
export const FILTER_PRODUCTS_FAILURE = 'FILTER_PRODUCTS_FAILURE';

export const GET_BY_CATEGORY_SUCCESS = 'GET_BY_CATEGORY_SUCCESS';
export const GET_BY_CATEGORY_FAILURE = 'GET_BY_CATEGORY_FAILURE';

export const QUICK_SEARCH_SUCCESS = 'QUICK_SEARCH_SUCCESS';
export const QUICK_SEARCH_FAILURE = 'QUICK_SEARCH_FAILURE';

export const ASSOCIATE_TO_PRODUCT_SUCCESS = 'ASSOCIATE_TO_PRODUCT_SUCCESS';
export const ASSOCIATE_TO_PRODUCT_FAILURE = 'ASSOCIATE_TO_PRODUCT_FAILURE';

export const REFRESH_TIERPRICES_SUCCESS = 'REFRESH_TIERPRICES_SUCCESS';
export const REFRESH_TIERPRICES_FAILURE = 'REFRESH_TIERPRICES_FAILURE';

export const PRODUCT_PAYLOAD = 'PRODUCT_PAYLOAD';

export const DELETE_PARENT_PRODUCT_IMAGE_SUCCESS = 'DELETE_PARENT_PRODUCT_IMAGE_SUCCESS';
export const DELETE_PARENT_PRODUCT_IMAGE_FAILURE = 'DELETE_PARENT_PRODUCT_IMAGE_FAILURE';

export const DELETE_PARENT_PRODUCT_VIDEO_SUCCESS = 'DELETE_PARENT_PRODUCT_VIDEO_SUCCESS';
export const DELETE_PARENT_PRODUCT_VIDEO_FAILURE = 'DELETE_PARENT_PRODUCT_VIDEO_FAILURE';

export const DOWNLOAD_ORDERS_SUCCESS = 'DOWNLOAD_ORDERS_SUCCESS';
export const DOWNLOAD_ORDERS_FAILURE = 'DOWNLOAD_ORDERS_FAILURE';

export const UPDATE_PRODUCT_SORT_SUCCESS = 'UPDATE_PRODUCT_SORT_SUCCESS';
export const UPDATE_PRODUCT_SORT_FAILURE = 'UPDATE_PRODUCT_SORT_FAILURE';

// Product Form

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

// Suppliers

export const SUPPLIERS_GET_SUCCESS = 'SUPPLIERS_GET_SUCCESS';
export const SUPPLIERS_GET_FAILURE = 'SUPPLIERS_GET_FAILURE';

export const SUPPLIER_SAVE_SUCCESS = 'SUPPLIER_SAVE_SUCCESS';
export const SUPPLIER_SAVE_FAILURE = 'SUPPLIER_SAVE_FAILURE';

export const SEARCH_SUPPLIERS = 'SEARCH_SUPPLIERS';

// PUBLISH

export const PUBLISH_CHANNEL_SUCCESS = 'PUBLISH_CHANNEL_SUCCESS';
export const PUBLISH_CHANNEL_FAILURE = 'PUBLISH_CHANNEL_FAILURE';

// NOTIFICATIONS

export const NOTIFICATIONS_GET_SUCCESS = 'NOTIFICATIONS_GET_SUCCESS';
export const NOTIFICATIONS_GET_FAILURE = 'NOTIFICATIONS_GET_FAILURE';

export const NOTIFICATION_READ_SUCCESS = 'NOTIFICATION_READ_SUCCESS';
export const NOTIFICATION_READ_FAILURE = 'NOTIFICATION_READ_FAILURE';

// ICONS

export const ICONS_GET_SUCCESS = 'ICONS_GET_SUCCESS';
export const ICONS_GET_FAILURE = 'ICONS_GET_FAILURE';

export const ICON_SAVE_SUCCESS = 'ICON_SAVE_SUCCESS';
export const ICON_SAVE_FAILURE = 'ICON_SAVE_FAILURE';

export const ICON_UPDATE_SUCCESS = 'ICON_UPDATE_SUCCESS';
export const ICON_UPDATE_FAILURE = 'ICON_UPDATE_FAILURE';

export const ICON_DELETE_SUCCESS = 'ICON_DELETE_SUCCESS';
export const ICON_DELETE_FAILURE = 'ICON_DELETE_FAILURE';

export const UPDATE_ICON_SORT_SUCCESS = 'UPDATE_ICON_SORT_SUCCESS';
export const UPDATE_ICON_SORT_FAILURE = 'UPDATE_ICON_SORT_FAILURE';

// PUBLISH

export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_FAILURE = 'PUBLISH_FAILURE';

// SALES REPS

export const EDIT_REP = 'EDIT_REP';

export const CHANGE_REP = 'CHANGE_REP';

export const GET_SALESREPS_SUCCESS = 'GET_SALESREPS_SUCCESS';
export const GET_SALESREPS_FAILURE = 'GET_SALESREPS_FAILURE';

export const SAVE_SALESREPS_SUCCESS = 'SAVE_SALESREPS_SUCCESS';
export const SAVE_SALESREPS_FAILURE = 'SAVE_SALESREPS_FAILURE';

export const UPDATE_SALESREPS_SUCCESS = 'UPDATE_SALESREPS_SUCCESS';
export const UPDATE_SALESREPS_FAILURE = 'UPDATE_SALESREPS_FAILURE';

export const BULK_SALESREPS_SUCCESS = 'BULK_SALESREPS_SUCCESS';
export const BULK_SALESREPS_FAILURE = 'BULK_SALESREPS_FAILURE';

// Banners

export const BANNERS_GET_SUCCESS = 'BANNERS_GET_SUCCESS';
export const BANNERS_GET_FAILURE = 'BANNERS_GET_FAILURE';

export const BANNER_SAVE_SUCCESS = 'BANNER_SAVE_SUCCESS';
export const BANNER_SAVE_FAILURE = 'BANNER_SAVE_FAILURE';

export const BANNER_DELETE_SUCCESS = 'BANNER_DELETE_SUCCESS';
export const BANNER_DELETE_FAILURE = 'BANNER_DELETE_FAILURE';

export const BANNER_UPDATE_SUCCESS = 'BANNER_UPDATE_SUCCESS';
export const BANNER_UPDATE_FAILURE = 'BANNER_UPDATE_FAILURE';

// Slider

export const SLIDERS_GET_SUCCESS = 'SLIDERS_GET_SUCCESS';
export const SLIDERS_GET_FAILURE = 'SLIDERS_GET_FAILURE';

export const SLIDER_SAVE_SUCCESS = 'SLIDER_SAVE_SUCCESS';
export const SLIDER_SAVE_FAILURE = 'SLIDER_SAVE_FAILURE';

export const SLIDER_DELETE_SUCCESS = 'SLIDER_DELETE_SUCCESS';
export const SLIDER_DELETE_FAILURE = 'SLIDER_DELETE_FAILURE';

// Catalogs

export const CATALOGS_DELETE_SUCCESS = 'CATALOGS_DELETE_SUCCESS';
export const CATALOG_DELETE_FAILURE = 'CATALOG_DELETE_FAILURE';

export const CATALOGS_UPDATE_SUCCESS = 'CATALOGS_UPDATE_SUCCESS';
export const CATALOG_UPDATE_FAILURE = 'CATALOG_UPDATE_FAILURE';

export const CATALOGS_SAVE_SUCCESS = 'CATALOGS_SAVE_SUCCESS';
export const CATALOG_SAVE_FAILURE = 'CATALOG_SAVE_FAILURE';

// Videos

export const VIDEOS_DELETE_SUCCESS = 'VIDEOS_DELETE_SUCCESS';
export const VIDEOS_DELETE_FAILURE = 'VIDEOS_DELETE_FAILURE';

export const VIDEOS_UPDATE_SUCCESS = 'VIDEOS_UPDATE_SUCCESS';
export const VIDEOS_UPDATE_FAILURE = 'VIDEOS_UPDATE_FAILURE';

export const VIDEOS_SAVE_SUCCESS = 'VIDEOS_SAVE_SUCCESS';
export const VIDEOS_SAVE_FAILURE = 'VIDEOS_SAVE_FAILURE';

export const UPDATE_VIDEO_SORT_SUCCESS = 'UPDATE_VIDEO_SORT_SUCCESS';
export const UPDATE_VIDEO_SORT_FAILURE = 'UPDATE_VIDEO_SORT_FAILURE';

// Literature

export const LITERATURE_DELETE_SUCCESS = 'LITERATURE_DELETE_SUCCESS';
export const LITERATURE_DELETE_FAILURE = 'LITERATURE_DELETE_FAILURE';

export const LITERATURE_UPDATE_SUCCESS = 'LITERATURE_UPDATE_SUCCESS';
export const LITERATURE_UPDATE_FAILURE = 'LITERATURE_UPDATE_FAILURE';

export const LITERATURE_SAVE_SUCCESS = 'LITERATURE_SAVE_SUCCESS';
export const LITERATURE_SAVE_FAILURE = 'LITERATURE_SAVE_FAILURE';

// News

export const NEWS_DELETE_SUCCESS = 'NEWS_DELETE_SUCCESS';
export const NEWS_DELETE_FAILURE = 'NEWS_DELETE_FAILURE';

export const NEWS_UPDATE_SUCCESS = 'NEWS_UPDATE_SUCCESS';
export const NEWS_UPDATE_FAILURE = 'NEWS_UPDATE_FAILURE';

export const NEWS_SAVE_SUCCESS = 'NEWS_SAVE_SUCCESS';
export const NEWS_SAVE_FAILURE = 'NEWS_SAVE_FAILURE';

// Store Locator

export const STORE_LOCATOR_SUCCESS = 'STORE_LOCATOR_SUCCESS';
export const STORE_LOCATOR_FAILURE = 'STORE_LOCATOR_FAILURE';

export const ONLINE_RETAILERS_SUCCESS = 'ONLINE_RETAILERS_SUCCESS';
export const ONLINE_RETAILERS_FAILURE = 'ONLINE_RETAILERS_FAILURE';

export const STORE_LOCATOR_DELETE_SUCCESS = 'STORE_LOCATOR_DELETE_SUCCESS';
export const STORE_LOCATOR_DELETE_FAILURE = 'STORE_LOCATOR_DELETE_FAILURE';

export const STORE_LOCATOR_UPDATE_SUCCESS = 'STORE_LOCATOR_UPDATE_SUCCESS';
export const STORE_LOCATOR_UPDATE_FAILURE = 'STORE_LOCATOR_UPDATE_FAILURE';

export const STORE_LOCATOR_SAVE_SUCCESS = 'STORE_LOCATOR_SAVE_SUCCESS';
export const STORE_LOCATOR_SAVE_FAILURE = 'STORE_LOCATOR_SAVE_FAILURE';

export const SLIDE_IN_GET_SUCCESS = 'SLIDE_IN_GET_SUCCESS';
export const SLIDE_IN_GET_FAILURE = 'SLIDE_IN_GET_FAILURE';

export const SLIDE_IN_POST_SUCCESS = 'SLIDE_IN_POST_SUCCESS';
export const SLIDE_IN_POST_FAILURE = 'SLIDE_IN_POST_FAILURE';

export const SLIDE_IN_PUT_SUCCESS = 'SLIDE_IN_PUT_SUCCESS';
export const SLIDE_IN_PUT_FAILURE = 'SLIDE_IN_PUT_FAILURE';

export const SLIDE_IN_DELETE_SUCCESS = 'SLIDE_IN_DELETE_SUCCESS';
export const SLIDE_IN_DELETE_FAILURE = 'SLIDE_IN_DELETE_FAILURE';

export const CAREER_DELETE_SUCCESS = 'CAREER_DELETE_SUCCESS';
export const CAREER_DELETE_FAILURE = 'CAREER_DELETE_FAILURE';

export const CAREER_UPDATE_SUCCESS = 'CAREER_UPDATE_SUCCESS';
export const CAREER_UPDATE_FAILURE = 'CAREER_UPDATE_FAILURE';

export const CAREER_SAVE_SUCCESS = 'CAREER_SAVE_SUCCESS';
export const CAREER_SAVE_FAILURE = 'CAREER_SAVE_FAILURE';

export const SAVE_QUERY = 'SAVE_QUERY';
export const SAVE_VARIATION_QUERY = 'SAVE_VARIATION_QUERY';

export const CHANGE_VARIATION = 'CHANGE_VARIATION';

export const PRODUCTS_VARIATIONS_IMAGE_DELETE_SUCCESS = 'PRODUCTS_VARIATIONS_IMAGE_DELETE_SUCCESS';
export const PRODUCTS_VARIATIONS_IMAGE_DELETE_FAILURE = 'PRODUCTS_VARIATIONS_IMAGE_DELETE_FAILURE';

export const PRODUCTS_VARIATIONS_VIDEO_DELETE_SUCCESS = 'PRODUCTS_VARIATIONS_VIDEO_DELETE_SUCCESS';
export const PRODUCTS_VARIATIONS_VIDEO_DELETE_FAILURE = 'PRODUCTS_VARIATIONS_VIDEO_DELETE_FAILURE';

export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS';
export const REMOVE_QUESTION_FAILURE = 'REMOVE_QUESTION_FAILURE';
// options
export const ADD_OPTIONS_SUCCESS = 'ADD_OPTIONS_SUCCESS';
export const ADD_OPTIONS_FAILURE = 'ADD_OPTIONS_FAILURE';

export const GET_OPTIONS_SUCCESS = 'GET_OPTIONS_SUCCESS';
export const GET_OPTIONS_FAILURE = 'GET_OPTIONS_FAILURE';

export const DELETE_OPTION_SUCCESS = 'DELETE_OPTION_SUCCESS';
export const DELETE_OPTION_FAILURE = 'DELETE_OPTION_FAILURE';

export const UPDATE_OPTION_SUCCESS = 'UPDATE_OPTION_SUCCESS';
export const UPDATE_OPTION_FAILURE = 'UPDATE_OPTION_FAILURE';

export const DELETE_PARENT_OPTION_SUCCESS = 'DELETE_PARENT_OPTION_SUCCESS';
export const DELETE_PARENT_OPTION_FAILURE = 'DELETE_PARENT_OPTION_FAILURE';

export const GET_ALL_PRODUCTS_IN_SYSTEM_SUCCESS = 'GET_ALL_PRODUCTS_IN_SYSTEM_SUCCESS';
export const GET_ALL_PRODUCTS_IN_SYSTEM_FAILURE = 'GET_ALL_PRODUCTS_IN_SYSTEM_FAILURE';

export const GET_PRODUCTS_BY_OPTION_SUCCESS = 'GET_PRODUCTS_BY_OPTION_SUCCESS';
export const GET_PRODUCTS_BY_OPTION_FAILURE = 'GET_PRODUCTS_BY_OPTION_FAILURE';

export const RESET_SELECTED_OPTION_PRODUCTS = 'RESET_SELECTED_OPTION_PRODUCTS'

export const BULK_PRODUCT_OPTIONS_UPLOADING_SUCCESS = 'BULK_PRODUCT_OPTIONS_UPLOADING_SUCCESS';
export const BULK_PRODUCT_OPTIONS_UPLOADING_FAILURE = 'BULK_PRODUCT_OPTIONS_UPLOADING_FAILURE';

export const DELETE_VARIATION_ICON_SUCCESS = 'DELETE_VARIATION_ICON_SUCCESS';
export const DELETE_VARIATION_ICON_FAILURE = 'DELETE_VARIATION_ICON_FAILURE';

export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_FAILURE = 'GET_ALL_QUESTIONS_FAILURE';

export const BULK_UPDATE_QUESTIONS_SUCCESS = 'BULK_UPDATE_QUESTIONS_SUCCESS';
export const BULK_UPDATE_QUESTIONS_FAILURE = 'BULK_UPDATE_QUESTIONS_FAILURE';

export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE';

export const ANSWER_EMAIL_SUCCESS = 'ANSWER_EMAIL_SUCCESS';
export const ANSWER_EMAIL_FAILURE = 'ANSWER_EMAIL_FAILURE';

export const UPDATE_ATTRIBUTE_SORT_SUCCESS = 'UPDATE_ATTRIBUTE_SORT_SUCCESS';
export const UPDATE_ATTRIBUTE_SORT_FAILURE = 'UPDATE_ATTRIBUTE_SORT_FAILURE';

export const REMOVE_OPTION_DOCUMENT_SUCCESS = 'REMOVE_OPTION_DOCUMENT_SUCCESS';
export const REMOVE_OPTION_DOCUMENT_FAILURE = 'REMOVE_OPTION_DOCUMENT_FAILURE';

export const UPDATE_OPTION_DOCUMENT_SUCCESS = 'UPDATE_OPTION_DOCUMENT_SUCCESS';
export const UPDATE_OPTION_DOCUMENT_FAILURE = 'UPDATE_OPTION_DOCUMENT_FAILURE';

export const UPDATE_PROMOTIONAL_LITRATURE_SORT_SUCCESS = 'UPDATE_PROMOTIONAL_LITRATURE_SORT_SUCCESS';
export const UPDATE_PROMOTIONAL_LITRATURE_SORT_FAILURE = 'UPDATE_PROMOTIONAL_LITRATURE_SORT_FAILURE';

export const REMOVE_ASSOCIATED_PRODUCT_SUCCESS = 'REMOVE_ASSOCIATED_PRODUCT_SUCCESS';
export const REMOVE_ASSOCIATED_PRODUCT_FAILURE = 'REMOVE_ASSOCIATED_PRODUCT_FAILURE';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE';

export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS';
export const CREATE_CONTACTS_FAILURE = 'CREATE_CONTACTS_FAILURE';

export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const UPDATE_CONTACTS_FAILURE = 'UPDATE_CONTACTS_FAILURE';

//Accessories
 export const GET_ACCESSORIES_SUCCESS='GET_ACCESSORIES_SUCCESS'
 export const GET_ACCESSORIES_FAILURE='GET_ACCESSORIES_FAILURE'

 export const ADD_ACCESSORIES_FAILURE='ADD_ACCESSORIES_FAILURE'
 export const ADD_ACCESSORIES_SUCCESS='ADD_ACCESSORIES_FAILURE'

 export const DELETE_ACCESSORY_FAILURE='DELETE_ACCESSORY_FAILURE'
 export const DELETE_ACCESSORY_SUCCESS='DELETE_ACCESSORY_SUCCESS'

 export const GET_PRODUCTS_BY_ACCESSORY_FAILURE='GET_PRODUCTS_BY_ACCESSORY_FAILURE'
 export const GET_PRODUCTS_BY_ACCESSORY_SUCCESS='GET_PRODUCTS_BY_ACCESSORY_SUCCESS'

 export const RESET_SELECTED_ACCESSORY_PRODUCTS='RESET_SELECTED_ACCESSORY_PRODUCTS'

 export const UPDATE_ACCESSORY_DOCUMENT_FAILURE='UPDATE_ACCESSORY_DOCUMENT_FAILURE'
 export const UPDATE_ACCESSORY_DOCUMENT_SUCCESS='UPDATE_ACCESSORY_DOCUMENT_SUCCESS'

 export const UPDATE_ACCESSORY_FAILURE='UPDATE_ACCESSORY_FAILURE'
 export const UPDATE_ACCESSORY_SUCCESS='UPDATE_ACCESSORY_SUCCESS'
 
 //Portal
export const INVENTORY_ITEMS_SUCCESS = 'INVENTORY_ITEMS_SUCCESS';
export const INVENTORY_ITEMS_FAILURE = 'INVENTORY_ITEMS_FAILURE';

export const GET_INVENTORY_ITEM_SUCCESS = 'GET_INVENTORY_ITEM_SUCCESS';
export const GET_INVENTORY_ITEM_FAILURE = 'GET_INVENTORY_ITEM_FAILURE';
 
//Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILURE = 'GET_USER_DETAIL_FAILURE';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const RESET_USER_PASSWORD_SUCCESS = 'RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_FAILURE = 'RESET_USER_PASSWORD_FAILURE';

export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_FAILURE = 'CHANGE_USER_PASSWORD_FAILURE';

export const VERIFY_SEND_USERS_EMAIL_SUCCESS = 'VERIFY_SEND_USERS_EMAIL_SUCCESS';
export const VERIFY_SEND_USERS_EMAIL_FAILURE = 'CHANGE_USER_PASSWORD_FAILURE';

export const SEND_APPROVED_REP_EMAIL_SUCCESS = 'SEND_APPROVED_REP_EMAIL_SUCCESS';
export const SEND_APPROVED_REP_EMAIL_FAILURE = 'SEND_APPROVED_REP_EMAIL_FAILURE';

export const SEND_DECLINED_REP_EMAIL_SUCCESS = 'SEND_DECLINED_REP_EMAIL_SUCCESS';
export const SEND_DECLINED_REP_EMAIL_FAILURE = 'SEND_DECLINED_REP_EMAIL_FAILURE';


//Coupons
export const GET_COUPONS_SUCCESS = 'GET_COUPONS_SUCCESS';
export const GET_COUPONS_FAILURE = 'GET_COUPONS_FAILURE';

export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_FAILURE = 'ADD_COUPON_FAILURE';

export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS';
export const UPDATE_COUPON_FAILURE = 'UPDATE_COUPON_FAILURE';

export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAILURE = 'DELETE_COUPON_FAILURE';

//Websites
export const GET_WEBSITES_SUCCESS = 'GET_WEBSITES_SUCCESS';
export const GET_WEBSITES_FAILURE = 'GET_WEBSITES_FAILURE';

export const ADD_WEBSITE_SUCCESS = 'ADD_WEBSITE_SUCCESS';
export const ADD_WEBSITE_FAILURE = 'ADD_WEBSITE_FAILURE';

export const UPDATE_WEBSITE_SUCCESS = 'UPDATE_WEBSITE_SUCCESS';
export const UPDATE_WEBSITE_FAILURE = 'UPDATE_WEBSITE_FAILURE';

export const DELETE_WEBSITE_SUCCESS = 'DELETE_WEBSITE_SUCCESS';
export const DELETE_WEBSITE_FAILURE = 'DELETE_WEBSITE_FAILURE';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FALIURE = 'GET_ORDERS_FALIURE';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FALIURE = 'DELETE_ORDERS_FALIURE';

export const PDFS_GET_SUCCESS = 'PDFS_GET_SUCCESS';
export const PDFS_GET_FAILURE = 'PDFS_GET_FAILURE';

export const PDF_SAVE_SUCCESS = 'PDF_SAVE_SUCCESS';
export const PDF_SAVE_FAILURE = 'PDF_SAVE_FAILURE';

export const PDF_UPDATE_SUCCESS = 'PDF_UPDATE_SUCCESS';
export const PDF_UPDATE_FAILURE = 'PDF_UPDATE_FAILURE';

export const PDF_DELETE_SUCCESS = 'PDF_DELETE_SUCCESS';
export const PDF_DELETE_FAILURE = 'PDF_DELETE_FAILURE';

export const PDF_CHANGE_PASSWORD_SUCCESS = 'PDF_CHANGE_PASSWORD_SUCCESS';
export const PDF_CHANGE_PASSWORD_FAILURE = 'PDF_CHANGE_PASSWORD_FAILURE';

export const VERIFY_PDF_SUCCESS = 'VERIFY_PDF_SUCCESS';
export const VERIFY_PDF_FAILURE = 'VERIFY_PDF_FAILURE';

export const GET_MISSING_SAGE_PRODUCTS_SUCCESS = 'GET_MISSING_SAGE_PRODUCTS_SUCCESS';
export const GET_MISSING_SAGE_PRODUCTS_FALIURE = 'GET_MISSING_SAGE_PRODUCTS_FALIURE';